<template>
	<div>
		<div recycle="false" style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0;">
			<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; place-content: flex-start center; flex-shrink: 0; margin-bottom: 8.53333px; -webkit-box-pack: center; background-color: rgb(255, 255, 255); width: 100%;">
				<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; place-content: flex-start; flex-shrink: 0; cursor: pointer; width: 100%; height: 36.6933px; -webkit-box-pack: start; -webkit-box-align: center; align-items: center;" data-appeared="true"><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex: 1 1 0%; font-size: 13.6533px; -webkit-box-flex: 1; font-weight: bold; color: rgb(51, 51, 51); margin-left: 11.9467px;">小米众筹</span>
					<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; -webkit-box-align: center; align-items: center;"><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 9.38667px; line-height: 36.6933px; color: rgb(153, 153, 153); margin-right: 2.56px; text-align: center;">更多</span><img resizemode="stretch" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAMAAABg3Am1AAAAZlBMVEUAAACZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZmZlLhKZbAAAAInRSTlMAzMa8FwuFUwWNm6p3JqJvXsK3saZ+OCwRlksyH5NBr2hlo9XLKgAAAZNJREFUSMftlNlyozAURDkSi4TYwWAw2M7//+RQU5UZSQiSynP6haqrvn2Xloh+8UOUja7MMBdL/C12PfCJdmvuX9DjWrBDVpuejQC6JrniPzvAFONfXbU2uYCqPOfXwDDakWkGsZzxbyAy5QUXAc2pvpmO4UcPWYi/wLAG97ZnBIRWiTzZ+0MwHHeVIh7RCbLAGJPgFp1BmWN1TWeF7jp1LB7hw+UnksLuGnInYyD3LAbbMJXCbM/5RqyeZ73ydkBuZZTC8yIn9eZ0M9TLIxje0WXGRuUcv46LTm5Yqim9c9rThOyq1P+EzmupDvDlZPlknNMKfeS3pU3IfaMTly+QFj9uKXy90eN3k3v3n/vnVKEE6dzdje4eeUP0trGtHD299Pje3jYj9l/7LuCXaE9/dJNloX1fcxXm3w1t4LUXUAT5iYYsFJ/3jECNeD5VGkDHh/570FEYSQ5yUU77BVz8HZIaMM1nFfW4SRBZdIExB+R8q+u60C92pGV0CZVtgn+Q+hl9jfUjN52U/aCzOPrFj/AHO0QQg+evJ4UAAAAASUVORK5CYII=" style="display: flex; width: 14.5067px; height: 14.5067px; margin-right: 8.53333px;"></div>
				</div>
				<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-flow: row wrap; align-content: flex-start; flex-shrink: 0; padding: 0px 8.53333px 8.53333px;">
					<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; cursor: pointer; margin-bottom: 4.26667px; width: 100%; height: 127.147px; border-top-left-radius: 2.56px; border-top-right-radius: 2.56px; background-color: rgb(249, 243, 233); overflow: hidden;" data-appeared="true">
						<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; width: 100%; padding: 0px 11.0933px;">
							<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 60%; height: 102.4px;"><span numberoflines="2" style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: -webkit-box; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 13.6533px; margin-top: 12.8px; color: rgb(51, 51, 51); text-overflow: ellipsis; -webkit-line-clamp: 2; overflow: hidden;">云米破壁料理机</span><span numberoflines="1" style="white-space: nowrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 10.24px; margin-top: 2.56px; margin-bottom: 8.53333px; color: rgb(153, 153, 153); text-overflow: ellipsis; overflow: hidden;">超高转速，自动保温，智能预约，大马力电机</span>
								<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; -webkit-box-align: end; align-items: flex-end;"><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 8.53333px; line-height: 8.53333px; margin-bottom: 0.853333px; color: rgb(182, 9, 9);">¥</span><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12.8px; line-height: 12.8px; color: rgb(182, 9, 9);">699</span><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 8.53333px; line-height: 8.53333px; margin-bottom: 0.853333px; color: rgb(182, 9, 9);"></span></div>
							</div>
							<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 101.547px; height: 105.813px; margin-left: 8.53333px; margin-right: 8.53333px; padding-top: 12.8px;"><img placeholder="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg==" autoremovescheme="true" autoreplacedomain="true" autoscaling="true" autowebp="true" ignoregif="true" autocompress="true" highquality="true" compresssuffix="Q75,Q50" defaultheight="750rem" lazyload="false" autopixelratio="true" data-once="true" src="https://img.youpin.mi-img.com/800_pic/a5acfbfd179a29379114c0b5464e3745.png" style="display: flex; width: 101.547px; height: 101.547px;"></div>
						</div>
						<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0;">
							<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; place-content: flex-start space-between; flex-shrink: 0; margin-bottom: 5.12px; padding: 0px 12.8px; -webkit-box-pack: justify; font-size: 10.24px;">
								<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; -webkit-box-align: center; align-items: center; height: 10.24px;"><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 8.53333px; color: rgb(182, 9, 9); line-height: 8.53333px;">75</span><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 8.53333px; color: rgb(153, 153, 153); line-height: 8.53333px;"> 人支持</span></div>
								<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0;"><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 8.53333px; color: rgb(182, 9, 9); line-height: 8.53333px;">15%</span></div>
							</div>
							<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; margin-top: 2.56px; height: 3.41333px; overflow: hidden; background-color: rgb(225, 225, 225);">
								<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 45.6533px; height: 3.41333px; background-image: linear-gradient(90deg, rgb(249, 196, 6), rgb(243, 117, 17));"></div>
							</div>
						</div>
					</div>
					<div style="width:100%;border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0;">
						<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; cursor: pointer; width: 50%; height: 134.827px; margin-right: 2.56px; margin-top: -0.853333px; background-color: rgb(248, 248, 248); border-bottom-left-radius: 2.56px; overflow: hidden;">
							<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 50%; padding-left: 11.0933px; padding-right: 6.82667px;" data-appeared="true"><span numberoflines="1" style="white-space: nowrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12.8px; margin-top: 6.82667px; color: rgb(51, 51, 51); text-overflow: ellipsis; line-height: 22.1867px; overflow: hidden;">德尔玛无线光热除螨仪</span>
								<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex: 1 1 0%; -webkit-box-flex: 1; height: 85.3333px;">
									<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; -webkit-box-align: end; align-items: flex-end; width: 44.3733px; height: 17.0667px;"><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 8.53333px; color: rgb(182, 9, 9); line-height: 8.53333px;">¥</span><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12.8px; color: rgb(182, 9, 9); margin-bottom: -0.853333px; line-height: 12.8px;">699</span><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 8.53333px; line-height: 8.53333px; margin-bottom: 0.853333px; color: rgb(182, 9, 9);"></span></div>
									<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 76.8px; height: 76.8px; margin-top: 0px; margin-left: 12.8px;"><img placeholder="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg==" autoremovescheme="true" autoreplacedomain="true" autoscaling="true" autowebp="true" ignoregif="true" autocompress="true" highquality="true" compresssuffix="Q75,Q50" defaultheight="750rem" lazyload="false" autopixelratio="true" data-once="true" src="https://img.youpin.mi-img.com/800_pic/e4c3751cd33f52a9338bf0ed385ba17b.png" style="display: flex; width: 76.8px; height: 76.8px;"></div>
								</div>
							</div>
							<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0;">
								<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; place-content: flex-start space-between; flex-shrink: 0; margin-bottom: 4.26667px; padding: 0px 12.8px; -webkit-box-pack: justify; font-size: 10.24px;">
									<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; -webkit-box-align: center; align-items: center; height: 10.24px;"><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 8.53333px; color: rgb(182, 9, 9); line-height: 8.53333px;">1883</span><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 8.53333px; color: rgb(153, 153, 153); line-height: 8.53333px;"> 人支持</span><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 7.68px; margin-left: 5.12px; border-radius: 1.28px; height: 9.38667px; padding-left: 0.853333px; padding-right: 0.853333px; line-height: 9.38667px; color: rgb(255, 255, 255); text-align: center; background-color: rgb(255, 156, 0);">火</span></div>
									<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0;"><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 8.53333px; color: rgb(182, 9, 9); line-height: 8.53333px;">377%</span></div>
								</div>
								<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; margin-top: 2.56px; height: 3.41333px; overflow: hidden; background-color: rgb(225, 225, 225);">
									<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 151.04px; height: 3.41333px; background-image: linear-gradient(90deg, rgb(249, 196, 6), rgb(243, 117, 17));"></div>
								</div>
							</div>
						</div>
						<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; cursor: pointer; width: 50%; height: 134.827px; margin-top: -0.853333px; background-color: rgb(248, 248, 248); border-bottom-right-radius: 2.56px; overflow: hidden;">
							<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 50%; padding-left: 11.0933px; padding-right: 6.82667px;" data-appeared="true"><span numberoflines="1" style="white-space: nowrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12.8px; margin-top: 6.82667px; color: rgb(51, 51, 51); text-overflow: ellipsis; line-height: 22.1867px; overflow: hidden;">圈厨多功能料理锅</span>
								<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex: 1 1 0%; -webkit-box-flex: 1; height: 85.3333px;">
									<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; -webkit-box-align: end; align-items: flex-end; width: 44.3733px; height: 17.0667px;"><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 8.53333px; color: rgb(182, 9, 9); line-height: 8.53333px;">¥</span><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 12.8px; color: rgb(182, 9, 9); margin-bottom: -0.853333px; line-height: 12.8px;">379</span><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 8.53333px; line-height: 8.53333px; margin-bottom: 0.853333px; color: rgb(182, 9, 9);"></span></div>
									<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 76.8px; height: 76.8px; margin-top: 0px; margin-left: 12.8px;"><img placeholder="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg==" autoremovescheme="true" autoreplacedomain="true" autoscaling="true" autowebp="true" ignoregif="true" autocompress="true" highquality="true" compresssuffix="Q75,Q50" defaultheight="750rem" lazyload="false" autopixelratio="true" data-once="true" src="https://img.youpin.mi-img.com/800_pic/3e1b663a71e04206d3fe169c686728df.png" style="display: flex; width: 76.8px; height: 76.8px;"></div>
								</div>
							</div>
							<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0;">
								<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; place-content: flex-start space-between; flex-shrink: 0; margin-bottom: 4.26667px; padding: 0px 12.8px; -webkit-box-pack: justify; font-size: 10.24px;">
									<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: horizontal; flex-direction: row; align-content: flex-start; flex-shrink: 0; -webkit-box-align: center; align-items: center; height: 10.24px;"><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 8.53333px; color: rgb(182, 9, 9); line-height: 8.53333px;">1407</span><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 8.53333px; color: rgb(153, 153, 153); line-height: 8.53333px;"> 人支持</span><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 7.68px; margin-left: 5.12px; border-radius: 1.28px; height: 9.38667px; padding-left: 0.853333px; padding-right: 0.853333px; line-height: 9.38667px; color: rgb(255, 255, 255); text-align: center; background-color: rgb(255, 128, 48);">热</span></div>
									<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0;"><span style="white-space: pre-wrap; border: 0px solid black; position: relative; box-sizing: border-box; display: block; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; font-size: 8.53333px; color: rgb(182, 9, 9); line-height: 8.53333px;">141%</span></div>
								</div>
								<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; margin-top: 2.56px; height: 3.41333px; overflow: hidden; background-color: rgb(225, 225, 225);">
									<div style="border: 0px solid black; position: relative; box-sizing: border-box; display: flex; -webkit-box-orient: vertical; flex-direction: column; align-content: flex-start; flex-shrink: 0; width: 151.04px; height: 3.41333px; background-image: linear-gradient(90deg, rgb(249, 196, 6), rgb(243, 117, 17));"></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

</template>

<script>
	import $ from 'jquery'
	window.$ = $;
	export default {
		data() {
			return {
				content3_news: []
			}
		},
		methods: {
			getNews: function() {
				var self = this;
				$.ajax({
					type: "POST",
					url: "http://localhost:4000/maincontent", //之前post请求不显示数据是因为把http写成了https
					success: function(data) {
						var goods = JSON.parse(data);
						console.log(goods);
						self.content3_news = goods.data.homepage.floors[3].data.items;
					}
				})
			}
		},
		mounted() {
			this.getNews();

		}
	}
</script>

<style>

</style>